# Site settings
title: theonlystephen 
email: me@theonlystephen.com 
url: https://swmcc.github.io
description: "Belfast developer - django, python, node, javascript, angular. All round good person."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: theonlystephen 
  location: Belfast
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/swmcc
  - title: github
    url: http://github.com/swmcc

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: 'Built using <a href="http://jekyllrb.com">Jekyll</a><br />Tested using <a href="http://mochajs.org/">mocha</a><br />Deployed using <a href="http://www.codeship.com">Codeship</a><br />Hosted on <a href="https://pages.github.com/">Github Pages</a><br />'

# Build settings
markdown: kramdown
permalink: pretty
